---
apiVersion: kubernetesinit.config.k8s.io/v1beta1
kind: KubernetesInit
namespace: hello-kubernetes
type: kustomize
retryLimit: 5
wait:
  - rollout status deployment/hello-kubernetes-hello-kubernetes
